# Generated by Django 2.2.6 on 2021-07-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
    ]
