# Generated by Django 2.2.6 on 2021-07-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_group_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
