# Generated by Django 2.2.9 on 2021-03-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210327_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Post Group'},
        ),
    ]
